"""add_lexicon_columns

Revision ID: 29d2d9199ae5
Revises: e031ca933426
Create Date: 2025-12-19 17:43:39.879310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d2d9199ae5'
down_revision: Union[str, Sequence[str], None] = 'e031ca933426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_extractions', sa.Column('action_signals', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('signal_extractions', sa.Column('compliance_signals', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_extractions', 'compliance_signals')
    op.drop_column('signal_extractions', 'action_signals')
    # ### end Alembic commands ###
