"""Add llm_configurations table

Revision ID: 353f9e4b8ea0
Revises: d0d3398d0750
Create Date: 2025-12-11 13:24:21.595852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353f9e4b8ea0'
down_revision: Union[str, Sequence[str], None] = 'd0d3398d0750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmconfigurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmconfigurations_provider'), 'llmconfigurations', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llmconfigurations_provider'), table_name='llmconfigurations')
    op.drop_table('llmconfigurations')
    # ### end Alembic commands ###
