"""Update_SignalExtraction_Model

Revision ID: 36c1c8fd89f7
Revises: 46ab9321994e
Create Date: 2025-12-11 12:10:28.683247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c1c8fd89f7'
down_revision: Union[str, Sequence[str], None] = '46ab9321994e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_extractions', sa.Column('llm_analysis_status', sa.String(), nullable=True))
    op.add_column('signal_extractions', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('signal_extractions', sa.Column('signals', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_extractions', 'signals')
    op.drop_column('signal_extractions', 'sentiment')
    op.drop_column('signal_extractions', 'llm_analysis_status')
    # ### end Alembic commands ###
