"""Fix_Model_Base_And_Add_LLM_Config

Revision ID: 46ab9321994e
Revises: 60149c5b6869
Create Date: 2025-12-11 11:54:36.079987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ab9321994e'
down_revision: Union[str, Sequence[str], None] = '60149c5b6869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmconfigurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmconfigurations_provider'), 'llmconfigurations', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llmconfigurations_provider'), table_name='llmconfigurations')
    op.drop_table('llmconfigurations')
    # ### end Alembic commands ###
