"""Initial_tables

Revision ID: 60149c5b6869
Revises: 
Create Date: 2025-12-11 11:50:26.683575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60149c5b6869'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('account_email', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('check_in_interval_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_email'), 'accounts', ['account_email'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('role_type', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('contract_name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('total_contract_value', sa.Float(), nullable=True),
    sa.Column('arr', sa.Float(), nullable=True),
    sa.Column('products_modules', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fedramp_required', sa.Boolean(), nullable=True),
    sa.Column('hipaa_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('request_score', sa.Integer(), nullable=True),
    sa.Column('relationship_score', sa.Integer(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('expansion_score', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_date', sa.DateTime(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('recipients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('input_id', sa.UUID(), nullable=False),
    sa.Column('churn_signals', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('positive_signals', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keyword_severity', sa.String(), nullable=True),
    sa.Column('llm_analyzed', sa.Boolean(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_extractions')
    op.drop_table('inputs')
    op.drop_table('health_scores')
    op.drop_table('contracts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_accounts_account_email'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
