"""add_contract_full_text

Revision ID: 8735841687c9
Revises: 29d2d9199ae5
Create Date: 2025-12-19 17:49:34.532184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8735841687c9'
down_revision: Union[str, Sequence[str], None] = '29d2d9199ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('full_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'full_text')
    # ### end Alembic commands ###
