"""Add_AI_Summary_HealthScore

Revision ID: b638c0c038fd
Revises: 36c1c8fd89f7
Create Date: 2025-12-11 12:18:56.350665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b638c0c038fd'
down_revision: Union[str, Sequence[str], None] = '36c1c8fd89f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_scores', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_scores', 'ai_summary')
    # ### end Alembic commands ###
