"""add_contracts_table

Revision ID: cc90b0ed172f
Revises: b638c0c038fd
Create Date: 2025-12-11 13:00:13.959970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc90b0ed172f'
down_revision: Union[str, Sequence[str], None] = 'b638c0c038fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llmconfigurations_provider'), table_name='llmconfigurations')
    op.drop_table('llmconfigurations')
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('term_length', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('primary_signer', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('updated_at', sa.Date(), nullable=True))
    op.alter_column('contracts', 'total_contract_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('contracts', 'arr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_contracts_account_id'), 'contracts', ['account_id'], unique=False)
    op.create_index(op.f('ix_contracts_end_date'), 'contracts', ['end_date'], unique=False)
    op.drop_column('contracts', 'fedramp_required')
    op.drop_column('contracts', 'hipaa_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('hipaa_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('fedramp_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contracts_end_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_account_id'), table_name='contracts')
    op.alter_column('contracts', 'arr',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('contracts', 'total_contract_value',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'primary_signer')
    op.drop_column('contracts', 'term_length')
    op.drop_column('accounts', 'created_at')
    op.create_table('llmconfigurations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_key_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('llmconfigurations_pkey'))
    )
    op.create_index(op.f('ix_llmconfigurations_provider'), 'llmconfigurations', ['provider'], unique=False)
    # ### end Alembic commands ###
