"""add_contract_document_path

Revision ID: ccc7a916d6c0
Revises: 8735841687c9
Create Date: 2025-12-19 17:55:09.014639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc7a916d6c0'
down_revision: Union[str, Sequence[str], None] = '8735841687c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('document_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'document_path')
    # ### end Alembic commands ###
